buildscript {
    repositories {
        maven { url = 'https://bmclapi2.bangbang93.com/maven/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.74'
    }
}
rootProject.name = 'aicompanion'
