modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="deepseek"
version="${file.jarVersion}"
displayName="DeepSeek｜鲸鱼娘AI助手"
description='''一只蓝白色鲸鱼娘形象的生存AI助手：会跟随你、和你聊天（接入大模型）、帮你建造（自带合成台、建筑定位火把定位）、整理箱子、回答整合包问题。'''
authors="Elena"

[[dependencies.deepseek]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.deepseek]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
